---
version: "2.0"
services:
  emotion-copilot:
    image: yuvrajgupta1808/emotion-copilot:v4
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
      - port: 8080
        as: 8080
        to:
          - global: true
      - port: 8081
        as: 8081
        to:
          - global: true
    env:
      - VENICE_API_KEY=VENICE-ADMIN-KEY-xRRSEMPQQe8-DkpTGZTEQOilbmgykuUUc6v5_-pJkT
profiles:
  compute:
    emotion-copilot:
      resources:
        cpu:
          units: 1
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        emotion-copilot:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
        allOf: []
deployment:
  emotion-copilot:
    dcloud:
      profile: emotion-copilot
      count: 1
